[tool.poetry]
name = "taskiq-redis"
version = "0.1.0"
description = ""
authors = ["taskiq-team"]

[tool.poetry.dependencies]
python = "^3.7"
taskiq = { git = "https://github.com/taskiq-python/taskiq", branch = "master" }
redis = "4.3.4"
types-redis = "^4.3.12"
flake8 = "^4.0.1"

[tool.poetry.dev-dependencies]
pytest = "^7.0"
flake8 = "^4.0.1"
mypy = "^0.961"
isort = "^5.10.1"
yesqa = "^1.3.0"
wemake-python-styleguide = "^0.16.1"
black = "^22.3.0"
autoflake = "^1.4"
pytest-cov = "^3.0.0"
anyio = "^3.6.1"
pytest-env = "^0.6.2"
fakeredis = "^1.8.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
