name: Testing taskiq-redis

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  lint:
    strategy:
      matrix:
        cmd:
          - black
          - flake8
          - isort
          # mypy is disabled because redis>=5.0 has errors in typing
          # - mypy
          - autoflake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "poetry"
      - name: Install deps
        run: poetry install
      - name: Run lint check
        run: poetry run pre-commit run -a ${{ matrix.cmd }}
  pytest:
    services:
      redis:
        image: bitnami/redis:6.2.5
        env:
          ALLOW_EMPTY_PASSWORD: "yes"
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=30
        ports:
          - 6379:6379
    strategy:
      matrix:
        py_version: ["3.8", "3.9", "3.10", "3.11"]
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.py_version }}"
      - name: Update pip
        run: python -m pip install -U pip
      - name: Install poetry
        run: python -m pip install poetry
      - name: Install deps
        run: poetry install
        env:
          POETRY_VIRTUALENVS_CREATE: false
      - name: Run pytest check
        run: poetry run pytest -vv -n auto --cov="taskiq_redis" .
      - name: Generate report
        run: poetry run coverage xml
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
        if: matrix.py_version == '3.9'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
